### ISSUE TITLE
logs file not found

### ISSUE THREAD

**Issue by youssefbar** [elieJalbout/Clustering-with-Deep-learning#14]
when the following command is run : 
 python main.py -d MNIST -a 1 --visualize 
the following error appears  : 
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from network import DCJC, rootLogger
  File "/content/Clustering-with-Deep-learning-master/network.py", line 29, in <module>
    fileHandler = logging.FileHandler(datetime.now().strftime('logs/dcjc_%H_%M_%d_%m.log'))
  File "/usr/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/content/Clustering-with-Deep-learning-master/logs/dcjc_16_53_28_07.log'

**Comment by hui-0608** [comment]
@youssefbar I encountered the same error, did you solve this problem?
