### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Deconv2DLayer'

### ISSUE THREAD

**Issue by rezacsedu** [elieJalbout/Clustering-with-Deep-learning#3]
When I try to start the training on MNIST using '$ python main.py -d MNIST -a 1 --pretrain 10', I experience the following error saying AttributeError: 'module' object has no attribute 'Deconv2DLayer'. However, I have configured all the dependencies. Here is the Traceback: 

[05/17 02:31:58]  Loading dataset
[05/17 02:31:59]  Done loading dataset
[05/17 02:31:59]  Creating network
Traceback (most recent call last):
  File "main.py", line 160, in <module>
    testOnlyClusterInitialization(dataset_name, archs[arch_index], args.pretrain)
  File "main.py", line 26, in testOnlyClusterInitialization
    dcjc = DCJC(arch_copy)
  File "/home/root/Downloads/Clustering-with-Deep-learning-master/network.py", line 47, in __init__
    self.network = netbuilder.buildNetwork()
  File "/home/root/Downloads/Clustering-with-Deep-learning-master/network.py", line 358, in buildNetwork
    network = self.processLayer(network, layer)
  File "/home/root/Downloads/Clustering-with-Deep-learning-master/network.py", line 481, in processLayer
    network = lasagne.layers.Deconv2DLayer(network, num_filters=layer_definition['num_filters'], filter_size=tuple(layer_definition['filter_size']), crop=layer_definition['conv_mode'], nonlinearity=self.getNonLinearity(layer_definition['non_linearity']), name=self.getLayerName(layer_definition))
AttributeError: 'module' object has no attribute 'Deconv2DLayer'

**Comment by ElieAljalbout** [comment]
That probably has to do with your version of Lasagne, try to update to the latest version and retry.

**Comment by rezacsedu** [comment]
@elieJalbout, sorry to bother again but which version of theano and lasagne have you used? I'm using lasagne 0.2.dev1 and theano 1.0.1 respectively. 

Help/pointer/clue would be appreciated. TIA
