### ISSUE TITLE
TypeError: ('An update must have the same type as the original shared variable (shared_var=W, shared_var.type=TensorType(float32, matrix), update_val=Elemwise{add,no_inplace}.0, update_val.type=TensorType(float64, matrix)).', 'If the difference is related to the broadcast pattern, you can call the tensor.unbroadcast(var, axis_to_unbroadcast[, ...]) function to remove broadcastable dimensions.')

### ISSUE THREAD

**Issue by rezacsedu** [elieJalbout/Clustering-with-Deep-learning#4]
Hi there,

I have pretrained the network first using the following command  "$ python main.py -d MNIST -a 1 --pretrain 15". Then the pretraining was completed successfully as shown below: 

[05/28 01:25:15]  Loading dataset
[05/28 01:25:21]  Done loading dataset
[05/28 01:25:21]  Creating network
[05/28 01:25:21]  Network: 50[5x5] 50[5x5]_bn 50[5x5]_bn_nonlin max[2x2] 50[5x5] 50[5x5]_bn 50[5x5]_bn_nonlin max[2x2] 120[4x4] 120[4x4]_bn 120[4x4]_bn_nonlin 50[4x4] 50[4x4]_bn 50[4x4]_bn_nonlin ups*[2x2] 50[5x5] 50[5x5]_bn 50[5x5]_bn_nonlin ups*[2x2] 1[5x5]
[05/28 01:25:26]  Done creating network
[05/28 01:25:26]  Starting training
[05/28 01:34:50]  1/15 [0.1403]                                           
[05/28 01:46:44]  2/15 [0.1395]                                             0.570        0.499
[05/28 01:55:43]  3/15 [0.1391]                                           
[05/28 02:07:21]  4/15 [0.1388]                                             0.580        0.507
[05/28 02:17:44]  5/15 [0.1385]                                           
[05/28 02:30:27]  6/15 [0.1382]                                             0.590        0.513
[05/28 02:40:48]  7/15 [0.1379]                                           
[05/28 02:52:52]  8/15 [0.1376]                                             0.586        0.511
[05/28 03:04:32]  9/15 [0.1372]                                           
[05/28 03:17:42]  10/15 [0.1369]                                            0.590        0.514
[05/28 03:31:20]  11/15 [0.1366]                                          
[05/28 03:43:34]  12/15 [0.1363]                                            0.570        0.498
[05/28 03:54:51]  13/15 [0.1360]                                          
[05/28 04:10:35]  14/15 [0.1358]                                            0.586        0.510
[05/28 04:20:31]  15/15 [0.1355]        

Then I tried to refine the autoencoder for specified #epochs as specified above as follows "python main.py -d MNIST -a 1 --cluster 15". However, I'm experiencing the following errors:

[05/28 05:57:40]  Loading dataset
[05/28 05:57:41]  Done loading dataset
[05/28 05:57:41]  Creating network
[05/28 05:57:41]  Network: 50[5x5] 50[5x5]_bn 50[5x5]_bn_nonlin max[2x2] 50[5x5] 50[5x5]_bn 50[5x5]_bn_nonlin max[2x2] 120[4x4] 120[4x4]_bn 120[4x4]_bn_nonlin 50[4x4] 50[4x4]_bn 50[4x4]_bn_nonlin ups*[2x2] 50[5x5] 50[5x5]_bn 50[5x5]_bn_nonlin ups*[2x2] 1[5x5]
[05/28 05:57:46]  Starting cluster improvement
[05/28 05:58:30]  Initial                                                   0.571        0.499
Traceback (most recent call last):
  File "main.py", line 164, in <module>
    testOnlyClusterImprovement(dataset_name, archs[arch_index], args.cluster, "KLD")
  File "main.py", line 55, in testOnlyClusterImprovement
    dcjc.doClusteringWithKLdivLoss(dataset, True, epochs)
  File "/home/asif/Downloads/Clustering-with-Deep-learning-master/network.py", line 183, in doClusteringWithKLdivLoss
    trainFunction = theano.function([self.t_input, self.t_target, P], total_loss, updates=updates)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/pfunc.py", line 449, in pfunc
    no_default_updates=no_default_updates)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/pfunc.py", line 208, in rebuild_collect_shared
    raise TypeError(err_msg, err_sug)
TypeError: ('An update must have the same type as the original shared variable (shared_var=W, shared_var.type=TensorType(float32, matrix), update_val=Elemwise{add,no_inplace}.0, update_val.type=TensorType(float64, matrix)).', 'If the difference is related to the broadcast pattern, you can call the tensor.unbroadcast(var, axis_to_unbroadcast[, ...]) function to remove broadcastable dimensions.')

Perhamps, I am doing it wrong way. Any pointer would be appreciated. Thanks.

**Comment by ElieAljalbout** [comment]
check https://github.com/Theano/Theano/issues/6551

**Comment by atoultaro** [comment]
I'm having the same problem as the original post when putting the "--cluster" command option. Could anyone kindly enlighten me how to solve it? Thanks.
